### PR TITLE
Use prop-types

### PR DESCRIPTION
**Pull request by skipsuva**

### CODE REVIEW

**Comment by JonghunYu** [comment]
@skipsuva Thanks for the contribution.

**Comment by skipsuva** [comment]
@JonghunYu np, thanks for the cool project!

**Comment by JonghunYu** [comment]
@vinayr please publish the latest version.

**Comment by vinayr** [comment]
@JonghunYu added you as owner. You can now publish to npm.
https://www.npmjs.com/package/react-native-simple-gauge

**Comment by JonghunYu** [comment]
I appreciate it and published

**Pull request merged**
